import { MatchupStats } from '../../matchupStats';
export const matchupStatsTestObj: MatchupStats = {
    "games": [
        {
            "id": 10,
            "week": 2,
            "awayTeam": {
                "id": 1,
                "name": "Iowa HerkysHeroes47",
                "abbr": "IHH47",
                "owner": {
                    "id": 1,
                    "firstName": "Brian",
                    "lastInitial": "D",
                    "division": "upstairs"
                },
                "year": "2011",
                "division": "upstairs",
                "standing": 1,
                "gamesPlayed": 16,
                "wins": 9,
                "winsRegSeason": 8,
                "losses": 7,
                "lossesRegSeason": 5,
                "ties": 0,
                "divisionWinner": "shared",
                "champion": false,
                "pointsFor": 1545,
                "pointsAgainst": 1323.5
            },
            "awayScore": 108,
            "homeTeam": {
                "id": 2,
                "name": "Westside Whales",
                "abbr": "WW",
                "owner": {
                    "id": 2,
                    "firstName": "Nick",
                    "lastInitial": "D",
                    "division": "downstairs"
                },
                "year": "2011",
                "division": "downstairs",
                "standing": 1,
                "gamesPlayed": 15,
                "wins": 11,
                "winsRegSeason": 10,
                "losses": 4,
                "lossesRegSeason": 3,
                "ties": 0,
                "divisionWinner": "outright",
                "champion": false,
                "pointsFor": 1369,
                "pointsAgainst": 1235
            },
            "homeScore": 126.5,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 50,
            "week": 10,
            "awayTeam": {
                "id": 2,
                "name": "Westside Whales",
                "abbr": "WW",
                "owner": {
                    "id": 2,
                    "firstName": "Nick",
                    "lastInitial": "D",
                    "division": "downstairs"
                },
                "year": "2011",
                "division": "downstairs",
                "standing": 1,
                "gamesPlayed": 15,
                "wins": 11,
                "winsRegSeason": 10,
                "losses": 4,
                "lossesRegSeason": 3,
                "ties": 0,
                "divisionWinner": "outright",
                "champion": false,
                "pointsFor": 1369,
                "pointsAgainst": 1235
            },
            "awayScore": 79.5,
            "homeTeam": {
                "id": 1,
                "name": "Iowa HerkysHeroes47",
                "abbr": "IHH47",
                "owner": {
                    "id": 1,
                    "firstName": "Brian",
                    "lastInitial": "D",
                    "division": "upstairs"
                },
                "year": "2011",
                "division": "upstairs",
                "standing": 1,
                "gamesPlayed": 16,
                "wins": 9,
                "winsRegSeason": 8,
                "losses": 7,
                "lossesRegSeason": 5,
                "ties": 0,
                "divisionWinner": "shared",
                "champion": false,
                "pointsFor": 1545,
                "pointsAgainst": 1323.5
            },
            "homeScore": 103,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 85,
            "week": 2,
            "awayTeam": {
                "id": 11,
                "name": "Iowa HerkysHeroes47",
                "abbr": "IHH47",
                "owner": {
                    "id": 1,
                    "firstName": "Brian",
                    "lastInitial": "D",
                    "division": "upstairs"
                },
                "year": "2012",
                "division": "upstairs",
                "standing": 3,
                "gamesPlayed": 16,
                "wins": 9,
                "winsRegSeason": 7,
                "losses": 7,
                "lossesRegSeason": 6,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1457.5,
                "pointsAgainst": 1409
            },
            "awayScore": 99.5,
            "homeTeam": {
                "id": 12,
                "name": "Westside Whales",
                "abbr": "WW",
                "owner": {
                    "id": 2,
                    "firstName": "Nick",
                    "lastInitial": "D",
                    "division": "downstairs"
                },
                "year": "2012",
                "division": "downstairs",
                "standing": 5,
                "gamesPlayed": 16,
                "wins": 5,
                "winsRegSeason": 4,
                "losses": 10,
                "lossesRegSeason": 8,
                "ties": 1,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1270.5,
                "pointsAgainst": 1494
            },
            "homeScore": 67.5,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 125,
            "week": 10,
            "awayTeam": {
                "id": 12,
                "name": "Westside Whales",
                "abbr": "WW",
                "owner": {
                    "id": 2,
                    "firstName": "Nick",
                    "lastInitial": "D",
                    "division": "downstairs"
                },
                "year": "2012",
                "division": "downstairs",
                "standing": 5,
                "gamesPlayed": 16,
                "wins": 5,
                "winsRegSeason": 4,
                "losses": 10,
                "lossesRegSeason": 8,
                "ties": 1,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1270.5,
                "pointsAgainst": 1494
            },
            "awayScore": 84.5,
            "homeTeam": {
                "id": 11,
                "name": "Iowa HerkysHeroes47",
                "abbr": "IHH47",
                "owner": {
                    "id": 1,
                    "firstName": "Brian",
                    "lastInitial": "D",
                    "division": "upstairs"
                },
                "year": "2012",
                "division": "upstairs",
                "standing": 3,
                "gamesPlayed": 16,
                "wins": 9,
                "winsRegSeason": 7,
                "losses": 7,
                "lossesRegSeason": 6,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1457.5,
                "pointsAgainst": 1409
            },
            "homeScore": 94,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 164,
            "week": 2,
            "awayTeam": {
                "id": 21,
                "name": "Iowa HerkysHeroes47",
                "abbr": "IHH47",
                "owner": {
                    "id": 1,
                    "firstName": "Brian",
                    "lastInitial": "D",
                    "division": "upstairs"
                },
                "year": "2013",
                "division": "upstairs",
                "standing": 1,
                "gamesPlayed": 15,
                "wins": 9,
                "winsRegSeason": 9,
                "losses": 6,
                "lossesRegSeason": 4,
                "ties": 0,
                "divisionWinner": "outright",
                "champion": false,
                "pointsFor": 1293.5,
                "pointsAgainst": 1275
            },
            "awayScore": 82,
            "homeTeam": {
                "id": 22,
                "name": "Westside Whales",
                "abbr": "WW",
                "owner": {
                    "id": 2,
                    "firstName": "Nick",
                    "lastInitial": "D",
                    "division": "downstairs"
                },
                "year": "2013",
                "division": "downstairs",
                "standing": 5,
                "gamesPlayed": 16,
                "wins": 4,
                "winsRegSeason": 3,
                "losses": 12,
                "lossesRegSeason": 10,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1101.5,
                "pointsAgainst": 1382
            },
            "homeScore": 79,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 204,
            "week": 10,
            "awayTeam": {
                "id": 22,
                "name": "Westside Whales",
                "abbr": "WW",
                "owner": {
                    "id": 2,
                    "firstName": "Nick",
                    "lastInitial": "D",
                    "division": "downstairs"
                },
                "year": "2013",
                "division": "downstairs",
                "standing": 5,
                "gamesPlayed": 16,
                "wins": 4,
                "winsRegSeason": 3,
                "losses": 12,
                "lossesRegSeason": 10,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1101.5,
                "pointsAgainst": 1382
            },
            "awayScore": 61.5,
            "homeTeam": {
                "id": 21,
                "name": "Iowa HerkysHeroes47",
                "abbr": "IHH47",
                "owner": {
                    "id": 1,
                    "firstName": "Brian",
                    "lastInitial": "D",
                    "division": "upstairs"
                },
                "year": "2013",
                "division": "upstairs",
                "standing": 1,
                "gamesPlayed": 15,
                "wins": 9,
                "winsRegSeason": 9,
                "losses": 6,
                "lossesRegSeason": 4,
                "ties": 0,
                "divisionWinner": "outright",
                "champion": false,
                "pointsFor": 1293.5,
                "pointsAgainst": 1275
            },
            "homeScore": 84,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 243,
            "week": 2,
            "awayTeam": {
                "id": 31,
                "name": "Iowa HerkysHeroes47",
                "abbr": "IHH47",
                "owner": {
                    "id": 1,
                    "firstName": "Brian",
                    "lastInitial": "D",
                    "division": "upstairs"
                },
                "year": "2014",
                "division": "upstairs",
                "standing": 3,
                "gamesPlayed": 16,
                "wins": 6,
                "winsRegSeason": 6,
                "losses": 10,
                "lossesRegSeason": 7,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1287,
                "pointsAgainst": 1437.5
            },
            "awayScore": 92.5,
            "homeTeam": {
                "id": 32,
                "name": "Westside Whales",
                "abbr": "WW",
                "owner": {
                    "id": 2,
                    "firstName": "Nick",
                    "lastInitial": "D",
                    "division": "downstairs"
                },
                "year": "2014",
                "division": "downstairs",
                "standing": 1,
                "gamesPlayed": 15,
                "wins": 9,
                "winsRegSeason": 8,
                "losses": 6,
                "lossesRegSeason": 5,
                "ties": 0,
                "divisionWinner": "shared",
                "champion": false,
                "pointsFor": 1424.5,
                "pointsAgainst": 1266
            },
            "homeScore": 75,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 283,
            "week": 10,
            "awayTeam": {
                "id": 32,
                "name": "Westside Whales",
                "abbr": "WW",
                "owner": {
                    "id": 2,
                    "firstName": "Nick",
                    "lastInitial": "D",
                    "division": "downstairs"
                },
                "year": "2014",
                "division": "downstairs",
                "standing": 1,
                "gamesPlayed": 15,
                "wins": 9,
                "winsRegSeason": 8,
                "losses": 6,
                "lossesRegSeason": 5,
                "ties": 0,
                "divisionWinner": "shared",
                "champion": false,
                "pointsFor": 1424.5,
                "pointsAgainst": 1266
            },
            "awayScore": 116.5,
            "homeTeam": {
                "id": 31,
                "name": "Iowa HerkysHeroes47",
                "abbr": "IHH47",
                "owner": {
                    "id": 1,
                    "firstName": "Brian",
                    "lastInitial": "D",
                    "division": "upstairs"
                },
                "year": "2014",
                "division": "upstairs",
                "standing": 3,
                "gamesPlayed": 16,
                "wins": 6,
                "winsRegSeason": 6,
                "losses": 10,
                "lossesRegSeason": 7,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1287,
                "pointsAgainst": 1437.5
            },
            "homeScore": 72.5,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 341,
            "week": 5,
            "awayTeam": {
                "id": 42,
                "name": "Westside Whales",
                "abbr": "WW",
                "owner": {
                    "id": 2,
                    "firstName": "Nick",
                    "lastInitial": "D",
                    "division": "downstairs"
                },
                "year": "2015",
                "division": "downstairs",
                "standing": 2,
                "gamesPlayed": 16,
                "wins": 10,
                "winsRegSeason": 8,
                "losses": 6,
                "lossesRegSeason": 5,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1368.5,
                "pointsAgainst": 1277
            },
            "awayScore": 60,
            "homeTeam": {
                "id": 41,
                "name": "Iowa HerkysHeroes47",
                "abbr": "IHH47",
                "owner": {
                    "id": 1,
                    "firstName": "Brian",
                    "lastInitial": "D",
                    "division": "upstairs"
                },
                "year": "2015",
                "division": "upstairs",
                "standing": 1,
                "gamesPlayed": 16,
                "wins": 10,
                "winsRegSeason": 9,
                "losses": 6,
                "lossesRegSeason": 4,
                "ties": 0,
                "divisionWinner": "shared",
                "champion": false,
                "pointsFor": 1522,
                "pointsAgainst": 1387
            },
            "homeScore": 87,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 391,
            "week": 16,
            "awayTeam": {
                "id": 42,
                "name": "Westside Whales",
                "abbr": "WW",
                "owner": {
                    "id": 2,
                    "firstName": "Nick",
                    "lastInitial": "D",
                    "division": "downstairs"
                },
                "year": "2015",
                "division": "downstairs",
                "standing": 2,
                "gamesPlayed": 16,
                "wins": 10,
                "winsRegSeason": 8,
                "losses": 6,
                "lossesRegSeason": 5,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1368.5,
                "pointsAgainst": 1277
            },
            "awayScore": 93.5,
            "homeTeam": {
                "id": 41,
                "name": "Iowa HerkysHeroes47",
                "abbr": "IHH47",
                "owner": {
                    "id": 1,
                    "firstName": "Brian",
                    "lastInitial": "D",
                    "division": "upstairs"
                },
                "year": "2015",
                "division": "upstairs",
                "standing": 1,
                "gamesPlayed": 16,
                "wins": 10,
                "winsRegSeason": 9,
                "losses": 6,
                "lossesRegSeason": 4,
                "ties": 0,
                "divisionWinner": "shared",
                "champion": false,
                "pointsFor": 1522,
                "pointsAgainst": 1387
            },
            "homeScore": 91,
            "gameType": "Consolation Game",
            "completed": true
        },
        {
            "id": 420,
            "week": 5,
            "awayTeam": {
                "id": 52,
                "name": "Westside Whales",
                "abbr": "WW",
                "owner": {
                    "id": 2,
                    "firstName": "Nick",
                    "lastInitial": "D",
                    "division": "downstairs"
                },
                "year": "2016",
                "division": "downstairs",
                "standing": 4,
                "gamesPlayed": 16,
                "wins": 8,
                "winsRegSeason": 5,
                "losses": 8,
                "lossesRegSeason": 8,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1229,
                "pointsAgainst": 1174
            },
            "awayScore": 83,
            "homeTeam": {
                "id": 51,
                "name": "Iowa HerkysHeroes47",
                "abbr": "IHH47",
                "owner": {
                    "id": 1,
                    "firstName": "Brian",
                    "lastInitial": "D",
                    "division": "upstairs"
                },
                "year": "2016",
                "division": "upstairs",
                "standing": 2,
                "gamesPlayed": 16,
                "wins": 10,
                "winsRegSeason": 8,
                "losses": 6,
                "lossesRegSeason": 5,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1503.5,
                "pointsAgainst": 1361.5
            },
            "homeScore": 103.5,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 499,
            "week": 5,
            "awayTeam": {
                "id": 62,
                "name": "Westside Whales",
                "abbr": "WW",
                "owner": {
                    "id": 2,
                    "firstName": "Nick",
                    "lastInitial": "D",
                    "division": "downstairs"
                },
                "year": "2017",
                "division": "downstairs",
                "standing": 5,
                "gamesPlayed": 16,
                "wins": 5,
                "winsRegSeason": 3,
                "losses": 11,
                "lossesRegSeason": 10,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1173.5,
                "pointsAgainst": 1391
            },
            "awayScore": 51.5,
            "homeTeam": {
                "id": 61,
                "name": "Iowa HerkysHeroes47",
                "abbr": "IHH47",
                "owner": {
                    "id": 1,
                    "firstName": "Brian",
                    "lastInitial": "D",
                    "division": "upstairs"
                },
                "year": "2017",
                "division": "upstairs",
                "standing": 1,
                "gamesPlayed": 16,
                "wins": 9,
                "winsRegSeason": 7,
                "losses": 7,
                "lossesRegSeason": 6,
                "ties": 0,
                "divisionWinner": "shared",
                "champion": false,
                "pointsFor": 1292,
                "pointsAgainst": 1310
            },
            "homeScore": 63,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 578,
            "week": 5,
            "awayTeam": {
                "id": 72,
                "name": "Westside Whales",
                "abbr": "WW",
                "owner": {
                    "id": 2,
                    "firstName": "Nick",
                    "lastInitial": "D",
                    "division": "downstairs"
                },
                "year": "2018",
                "division": "downstairs",
                "standing": 5,
                "gamesPlayed": 16,
                "wins": 3,
                "winsRegSeason": 2,
                "losses": 13,
                "lossesRegSeason": 11,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1301.2,
                "pointsAgainst": 1687.8
            },
            "awayScore": 99.7,
            "homeTeam": {
                "id": 71,
                "name": "Iowa HerkysHeroes47",
                "abbr": "IHH47",
                "owner": {
                    "id": 1,
                    "firstName": "Brian",
                    "lastInitial": "D",
                    "division": "upstairs"
                },
                "year": "2018",
                "division": "upstairs",
                "standing": 4,
                "gamesPlayed": 16,
                "wins": 6,
                "winsRegSeason": 5,
                "losses": 10,
                "lossesRegSeason": 8,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1531.7,
                "pointsAgainst": 1597.7
            },
            "homeScore": 111.8,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 626,
            "week": 15,
            "awayTeam": {
                "id": 72,
                "name": "Westside Whales",
                "abbr": "WW",
                "owner": {
                    "id": 2,
                    "firstName": "Nick",
                    "lastInitial": "D",
                    "division": "downstairs"
                },
                "year": "2018",
                "division": "downstairs",
                "standing": 5,
                "gamesPlayed": 16,
                "wins": 3,
                "winsRegSeason": 2,
                "losses": 13,
                "lossesRegSeason": 11,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1301.2,
                "pointsAgainst": 1687.8
            },
            "awayScore": 72.1,
            "homeTeam": {
                "id": 71,
                "name": "Iowa HerkysHeroes47",
                "abbr": "IHH47",
                "owner": {
                    "id": 1,
                    "firstName": "Brian",
                    "lastInitial": "D",
                    "division": "upstairs"
                },
                "year": "2018",
                "division": "upstairs",
                "standing": 4,
                "gamesPlayed": 16,
                "wins": 6,
                "winsRegSeason": 5,
                "losses": 10,
                "lossesRegSeason": 8,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1531.7,
                "pointsAgainst": 1597.7
            },
            "homeScore": 62,
            "gameType": "Consolation Game",
            "completed": true
        },
        {
            "id": 657,
            "week": 5,
            "awayTeam": {
                "id": 82,
                "name": "Westside Whales",
                "abbr": "WW",
                "owner": {
                    "id": 2,
                    "firstName": "Nick",
                    "lastInitial": "D",
                    "division": "downstairs"
                },
                "year": "2019",
                "division": "downstairs",
                "standing": 1,
                "gamesPlayed": 0,
                "wins": 0,
                "winsRegSeason": 0,
                "losses": 0,
                "lossesRegSeason": 0,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 0,
                "pointsAgainst": 0
            },
            "awayScore": 0,
            "homeTeam": {
                "id": 81,
                "name": "Iowa HerkysHeroes47",
                "abbr": "IHH47",
                "owner": {
                    "id": 1,
                    "firstName": "Brian",
                    "lastInitial": "D",
                    "division": "upstairs"
                },
                "year": "2019",
                "division": "upstairs",
                "standing": 1,
                "gamesPlayed": 0,
                "wins": 0,
                "winsRegSeason": 0,
                "losses": 0,
                "lossesRegSeason": 0,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 0,
                "pointsAgainst": 0
            },
            "homeScore": 0,
            "gameType": "Regular Season",
            "completed": false
        }
    ],
    "o1wins": 10,
    "o2wins": 4,
    "ties": 0,
    "o1points": 1201.3,
    "o2points": 1202.2999
}
