import { MatchupStats } from '../matchupStats';

export const MatchupStatsTestObj: MatchupStats = {
  "games":[
    {
      "id":39,"week":8,"awayTeam":{"id":3,"name":"Bustin' McNutts","abbr":"BMN","owner":{"id":3,"firstName":"Brian","lastInitial":"K","division":"upstairs"},"year":"2011","division":"upstairs","standing":4,"gamesPlayed":16,"wins":4,"winsRegSeason":3,"losses":12,"lossesRegSeason":10,"ties":0,"divisionWinner":null,"champion":false,"pointsFor":1257.5,"pointsAgainst":1446.5},"awayScore":60.5,"homeTeam":{"id":2,"name":"Westside Whales","abbr":"WW","owner":{"id":2,"firstName":"Nick","lastInitial":"D","division":"downstairs"},"year":"2011","division":"downstairs","standing":1,"gamesPlayed":15,"wins":11,"winsRegSeason":10,"losses":4,"lossesRegSeason":3,"ties":0,"divisionWinner":"outright","champion":false,"pointsFor":1369.0,"pointsAgainst":1235.0},"homeScore":66.5,"gameType":"Regular Season","completed":true
    },
    {
      "id":116,"week":8,"awayTeam":{"id":13,"name":"Don't Diss My Fiedorowicz","abbr":"DDMF","owner":{"id":3,"firstName":"Brian","lastInitial":"K","division":"upstairs"},"year":"2012","division":"upstairs","standing":5,"gamesPlayed":16,"wins":4,"winsRegSeason":1,"losses":12,"lossesRegSeason":12,"ties":0,"divisionWinner":null,"champion":false,"pointsFor":1211.5,"pointsAgainst":1377.5},"awayScore":60.0,"homeTeam":{"id":12,"name":"Westside Whales","abbr":"WW","owner":{"id":2,"firstName":"Nick","lastInitial":"D","division":"downstairs"},"year":"2012","division":"downstairs","standing":5,"gamesPlayed":16,"wins":5,"winsRegSeason":4,"losses":10,"lossesRegSeason":8,"ties":1,"divisionWinner":null,"champion":false,"pointsFor":1270.5,"pointsAgainst":1494.0},"homeScore":73.0,"gameType":"Regular Season","completed":true
    },
    {
      "id":145,"week":14,"awayTeam":{"id":13,"name":"Don't Diss My Fiedorowicz","abbr":"DDMF","owner":{"id":3,"firstName":"Brian","lastInitial":"K","division":"upstairs"},"year":"2012","division":"upstairs","standing":5,"gamesPlayed":16,"wins":4,"winsRegSeason":1,"losses":12,"lossesRegSeason":12,"ties":0,"divisionWinner":null,"champion":false,"pointsFor":1211.5,"pointsAgainst":1377.5},"awayScore":113.0,"homeTeam":{"id":12,"name":"Westside Whales","abbr":"WW","owner":{"id":2,"firstName":"Nick","lastInitial":"D","division":"downstairs"},"year":"2012","division":"downstairs","standing":5,"gamesPlayed":16,"wins":5,"winsRegSeason":4,"losses":10,"lossesRegSeason":8,"ties":1,"divisionWinner":null,"champion":false,"pointsFor":1270.5,"pointsAgainst":1494.0},"homeScore":97.0,"gameType":"Consolation Game","completed":true
    },
    {
      "id":155,"week":16,"awayTeam":{"id":13,"name":"Don't Diss My Fiedorowicz","abbr":"DDMF","owner":{"id":3,"firstName":"Brian","lastInitial":"K","division":"upstairs"},"year":"2012","division":"upstairs","standing":5,"gamesPlayed":16,"wins":4,"winsRegSeason":1,"losses":12,"lossesRegSeason":12,"ties":0,"divisionWinner":null,"champion":false,"pointsFor":1211.5,"pointsAgainst":1377.5},"awayScore":121.5,"homeTeam":{"id":12,"name":"Westside Whales","abbr":"WW","owner":{"id":2,"firstName":"Nick","lastInitial":"D","division":"downstairs"},"year":"2012","division":"downstairs","standing":5,"gamesPlayed":16,"wins":5,"winsRegSeason":4,"losses":10,"lossesRegSeason":8,"ties":1,"divisionWinner":null,"champion":false,"pointsFor":1270.5,"pointsAgainst":1494.0},"homeScore":72.5,"gameType":"Consolation Game","completed":true
    },
    {
      "id":195,"week":8,"awayTeam":{"id":23,"name":"Kaeptains of Fortetude","abbr":"KOF","owner":{"id":3,"firstName":"Brian","lastInitial":"K","division":"upstairs"},"year":"2013","division":"upstairs","standing":2,"gamesPlayed":16,"wins":10,"winsRegSeason":8,"losses":6,"lossesRegSeason":5,"ties":0,"divisionWinner":null,"champion":false,"pointsFor":1557.5,"pointsAgainst":1413.5},"awayScore":101.5,"homeTeam":{"id":22,"name":"Westside Whales","abbr":"WW","owner":{"id":2,"firstName":"Nick","lastInitial":"D","division":"downstairs"},"year":"2013","division":"downstairs","standing":5,"gamesPlayed":16,"wins":4,"winsRegSeason":3,"losses":12,"lossesRegSeason":10,"ties":0,"divisionWinner":null,"champion":false,"pointsFor":1101.5,"pointsAgainst":1382.0},"homeScore":53.5,"gameType":"Regular Season","completed":true
    },
    {
      "id":274,"week":8,"awayTeam":{"id":33,"name":"Harbaugh's Dad Pants","abbr":"HDP","owner":{"id":3,"firstName":"Brian","lastInitial":"K","division":"upstairs"},"year":"2014","division":"upstairs","standing":4,"gamesPlayed":16,"wins":7,"winsRegSeason":5,"losses":9,"lossesRegSeason":8,"ties":0,"divisionWinner":null,"champion":false,"pointsFor":1310.0,"pointsAgainst":1430.5},"awayScore":58.5,"homeTeam":{"id":32,"name":"Westside Whales","abbr":"WW","owner":{"id":2,"firstName":"Nick","lastInitial":"D","division":"downstairs"},"year":"2014","division":"downstairs","standing":1,"gamesPlayed":15,"wins":9,"winsRegSeason":8,"losses":6,"lossesRegSeason":5,"ties":0,"divisionWinner":"shared","champion":false,"pointsFor":1424.5,"pointsAgainst":1266.0},"homeScore":104.5,"gameType":"Regular Season","completed":true
    },
    {
      "id":368,"week":11,"awayTeam":{"id":42,"name":"Westside Whales","abbr":"WW","owner":{"id":2,"firstName":"Nick","lastInitial":"D","division":"downstairs"},"year":"2015","division":"downstairs","standing":2,"gamesPlayed":16,"wins":10,"winsRegSeason":8,"losses":6,"lossesRegSeason":5,"ties":0,"divisionWinner":null,"champion":false,"pointsFor":1368.5,"pointsAgainst":1277.0},"awayScore":61.5,"homeTeam":{"id":43,"name":"Play Ack-Shun Rollout","abbr":"PASR","owner":{"id":3,"firstName":"Brian","lastInitial":"K","division":"upstairs"},"year":"2015","division":"upstairs","standing":3,"gamesPlayed":16,"wins":9,"winsRegSeason":6,"losses":7,"lossesRegSeason":7,"ties":0,"divisionWinner":null,"champion":false,"pointsFor":1443.0,"pointsAgainst":1217.0},"homeScore":65.0,"gameType":"Regular Season","completed":true
    },
    {
      "id":447,"week":11,"awayTeam":{"id":52,"name":"Westside Whales","abbr":"WW","owner":{"id":2,"firstName":"Nick","lastInitial":"D","division":"downstairs"},"year":"2016","division":"downstairs","standing":4,"gamesPlayed":16,"wins":8,"winsRegSeason":5,"losses":8,"lossesRegSeason":8,"ties":0,"divisionWinner":null,"champion":false,"pointsFor":1229.0,"pointsAgainst":1174.0},"awayScore":63.5,"homeTeam":{"id":53,"name":"Live Free and Beathard","abbr":"LFAB","owner":{"id":3,"firstName":"Brian","lastInitial":"K","division":"upstairs"},"year":"2016","division":"upstairs","standing":5,"gamesPlayed":16,"wins":8,"winsRegSeason":6,"losses":8,"lossesRegSeason":7,"ties":0,"divisionWinner":null,"champion":false,"pointsFor":1379.5,"pointsAgainst":1302.5},"homeScore":97.0,"gameType":"Regular Season","completed":true
    },
    {
      "id":468,"week":15,"awayTeam":{"id":52,"name":"Westside Whales","abbr":"WW","owner":{"id":2,"firstName":"Nick","lastInitial":"D","division":"downstairs"},"year":"2016","division":"downstairs","standing":4,"gamesPlayed":16,"wins":8,"winsRegSeason":5,"losses":8,"lossesRegSeason":8,"ties":0,"divisionWinner":null,"champion":false,"pointsFor":1229.0,"pointsAgainst":1174.0},"awayScore":93.0,"homeTeam":{"id":53,"name":"Live Free and Beathard","abbr":"LFAB","owner":{"id":3,"firstName":"Brian","lastInitial":"K","division":"upstairs"},"year":"2016","division":"upstairs","standing":5,"gamesPlayed":16,"wins":8,"winsRegSeason":6,"losses":8,"lossesRegSeason":7,"ties":0,"divisionWinner":null,"champion":false,"pointsFor":1379.5,"pointsAgainst":1302.5},"homeScore":58.5,"gameType":"Consolation Game","completed":true
    },
    {
      "id":526,"week":11,"awayTeam":{"id":62,"name":"Westside Whales","abbr":"WW","owner":{"id":2,"firstName":"Nick","lastInitial":"D","division":"downstairs"},"year":"2017","division":"downstairs","standing":5,"gamesPlayed":16,"wins":5,"winsRegSeason":3,"losses":11,"lossesRegSeason":10,"ties":0,"divisionWinner":null,"champion":false,"pointsFor":1173.5,"pointsAgainst":1391.0},"awayScore":122.0,"homeTeam":{"id":63,"name":"You've Got to be Kittling Me","abbr":"YG2BKM","owner":{"id":3,"firstName":"Brian","lastInitial":"K","division":"upstairs"},"year":"2017","division":"upstairs","standing":1,"gamesPlayed":15,"wins":7,"winsRegSeason":7,"losses":8,"lossesRegSeason":6,"ties":0,"divisionWinner":"shared","champion":false,"pointsFor":1279.0,"pointsAgainst":1304.0},"homeScore":120.0,"gameType":"Regular Season","completed":true
    },
    {
      "id":605,"week":11,"awayTeam":{"id":72,"name":"Westside Whales","abbr":"WW","owner":{"id":2,"firstName":"Nick","lastInitial":"D","division":"downstairs"},"year":"2018","division":"downstairs","standing":5,"gamesPlayed":15,"wins":3,"winsRegSeason":2,"losses":12,"lossesRegSeason":11,"ties":0,"divisionWinner":null,"champion":false,"pointsFor":1231.3,"pointsAgainst":1582.4},"awayScore":75.4,"homeTeam":{"id":73,"name":"FANTastic TDs","abbr":"FTTD","owner":{"id":3,"firstName":"Brian","lastInitial":"K","division":"upstairs"},"year":"2018","division":"upstairs","standing":1,"gamesPlayed":14,"wins":11,"winsRegSeason":11,"losses":3,"lossesRegSeason":2,"ties":0,"divisionWinner":"outright","champion":false,"pointsFor":1532.2,"pointsAgainst":1235.9},"homeScore":111.9,"gameType":"Regular Season","completed":true
    }
  ],
  "o1wins":5,
  "o2wins":6,
  "ties":0,
  "o1points":919.4,
  "o2points":930.4
}
