import { Team } from '../team';

export const OwnerTeamsTestObj: Team[] = [
    {
        "id": 4,
        "name": "The Ricky Stanzis",
        "abbr": "RS",
        "owner": {
            "id": 4,
            "firstName": "Brad",
            "lastInitial": "L",
            "division": "upstairs"
        },
        "year": "2011",
        "division": "upstairs",
        "standing": 3,
        "gamesPlayed": 16,
        "wins": 8,
        "winsRegSeason": 7,
        "losses": 8,
        "lossesRegSeason": 6,
        "ties": 0,
        "divisionWinner": null,
        "champion": false,
        "pointsFor": 1376,
        "pointsAgainst": 1411
    },
    {
        "id": 24,
        "name": "The Ricky Stanzis",
        "abbr": "RS",
        "owner": {
            "id": 4,
            "firstName": "Brad",
            "lastInitial": "L",
            "division": "upstairs"
        },
        "year": "2013",
        "division": "upstairs",
        "standing": 5,
        "gamesPlayed": 16,
        "wins": 4,
        "winsRegSeason": 3,
        "losses": 12,
        "lossesRegSeason": 10,
        "ties": 0,
        "divisionWinner": null,
        "champion": false,
        "pointsFor": 1287.5,
        "pointsAgainst": 1553.5
    },
    {
        "id": 34,
        "name": "The Ricky Stanzis",
        "abbr": "RS",
        "owner": {
            "id": 4,
            "firstName": "Brad",
            "lastInitial": "L",
            "division": "upstairs"
        },
        "year": "2014",
        "division": "upstairs",
        "standing": 2,
        "gamesPlayed": 16,
        "wins": 9,
        "winsRegSeason": 7,
        "losses": 7,
        "lossesRegSeason": 6,
        "ties": 0,
        "divisionWinner": null,
        "champion": false,
        "pointsFor": 1485,
        "pointsAgainst": 1373
    },
    {
        "id": 44,
        "name": "The Ricky Stanzis",
        "abbr": "RS",
        "owner": {
            "id": 4,
            "firstName": "Brad",
            "lastInitial": "L",
            "division": "upstairs"
        },
        "year": "2015",
        "division": "upstairs",
        "standing": 5,
        "gamesPlayed": 16,
        "wins": 5,
        "winsRegSeason": 3,
        "losses": 11,
        "lossesRegSeason": 10,
        "ties": 0,
        "divisionWinner": null,
        "champion": false,
        "pointsFor": 1250,
        "pointsAgainst": 1486.5
    },
    {
        "id": 74,
        "name": "The Ricky Stanzis",
        "abbr": "RS",
        "owner": {
            "id": 4,
            "firstName": "Brad",
            "lastInitial": "L",
            "division": "upstairs"
        },
        "year": "2018",
        "division": "upstairs",
        "standing": 4,
        "gamesPlayed": 16,
        "wins": 6,
        "winsRegSeason": 5,
        "losses": 10,
        "lossesRegSeason": 8,
        "ties": 0,
        "divisionWinner": null,
        "champion": false,
        "pointsFor": 1339.7,
        "pointsAgainst": 1555
    },
    {
        "id": 14,
        "name": "The Ricky Stanzis",
        "abbr": "RS",
        "owner": {
            "id": 4,
            "firstName": "Brad",
            "lastInitial": "L",
            "division": "upstairs"
        },
        "year": "2012",
        "division": "upstairs",
        "standing": 1,
        "gamesPlayed": 15,
        "wins": 9,
        "winsRegSeason": 8,
        "losses": 6,
        "lossesRegSeason": 5,
        "ties": 0,
        "divisionWinner": "shared",
        "champion": false,
        "pointsFor": 1351,
        "pointsAgainst": 1289
    },
    {
        "id": 64,
        "name": "The Ricky Stanzis",
        "abbr": "RS",
        "owner": {
            "id": 4,
            "firstName": "Brad",
            "lastInitial": "L",
            "division": "upstairs"
        },
        "year": "2017",
        "division": "upstairs",
        "standing": 1,
        "gamesPlayed": 16,
        "wins": 7,
        "winsRegSeason": 7,
        "losses": 9,
        "lossesRegSeason": 6,
        "ties": 0,
        "divisionWinner": "shared",
        "champion": false,
        "pointsFor": 1337.5,
        "pointsAgainst": 1259
    },
    {
        "id": 54,
        "name": "The Ricky Stanzis",
        "abbr": "RS",
        "owner": {
            "id": 4,
            "firstName": "Brad",
            "lastInitial": "L",
            "division": "upstairs"
        },
        "year": "2016",
        "division": "upstairs",
        "standing": 1,
        "gamesPlayed": 15,
        "wins": 11,
        "winsRegSeason": 9,
        "losses": 4,
        "lossesRegSeason": 4,
        "ties": 0,
        "divisionWinner": "outright",
        "champion": true,
        "pointsFor": 1549,
        "pointsAgainst": 1411
    }
]
