import { AllTimeStats } from '../../allTimeStats';
export const standingsTestObj: AllTimeStats[] = [
    {
        "ownerId": 9,
        "firstname": "Sean",
        "lastinitial": "S",
        "seasons": 4,
        "wins": 37,
        "losses": 25,
        "ties": 0,
        "winningpct": 0.597,
        "pointsfor": 5463,
        "pointsagainst": 5018,
        "pointdifferential": 445,
        "pfpg": 88.1,
        "papg": 80.9,
        "ppgdiff": 7.2
    },
    {
        "ownerId": 11,
        "firstname": "Ryan",
        "lastinitial": "D",
        "seasons": 5,
        "wins": 36,
        "losses": 27,
        "ties": 0,
        "winningpct": 0.571,
        "pointsfor": 5796.7,
        "pointsagainst": 5532.6,
        "pointdifferential": 264.1001,
        "pfpg": 92,
        "papg": 87.8,
        "ppgdiff": 4.2
    },
    {
        "ownerId": 5,
        "firstname": "Matt",
        "lastinitial": "M",
        "seasons": 9,
        "wins": 71,
        "losses": 55,
        "ties": 0,
        "winningpct": 0.563,
        "pointsfor": 11259.1,
        "pointsagainst": 10742.3,
        "pointdifferential": 516.7998,
        "pfpg": 89.4,
        "papg": 85.3,
        "ppgdiff": 4.1
    },
    {
        "ownerId": 1,
        "firstname": "Brian",
        "lastinitial": "D",
        "seasons": 9,
        "wins": 68,
        "losses": 59,
        "ties": 0,
        "winningpct": 0.535,
        "pointsfor": 11432.2,
        "pointsagainst": 11101.2,
        "pointdifferential": 331,
        "pfpg": 90,
        "papg": 87.4,
        "ppgdiff": 2.6
    },
    {
        "ownerId": 6,
        "firstname": "Drew",
        "lastinitial": "M",
        "seasons": 9,
        "wins": 66,
        "losses": 59,
        "ties": 0,
        "winningpct": 0.528,
        "pointsfor": 10836.9,
        "pointsagainst": 11030.2,
        "pointdifferential": -193.2998,
        "pfpg": 86.7,
        "papg": 88.2,
        "ppgdiff": -1.5
    },
    {
        "ownerId": 8,
        "firstname": "Kyle",
        "lastinitial": "P",
        "seasons": 9,
        "wins": 65,
        "losses": 63,
        "ties": 0,
        "winningpct": 0.508,
        "pointsfor": 11225.2,
        "pointsagainst": 11052.2,
        "pointdifferential": 173,
        "pfpg": 87.7,
        "papg": 86.3,
        "ppgdiff": 1.4
    },
    {
        "ownerId": 3,
        "firstname": "Brian",
        "lastinitial": "K",
        "seasons": 9,
        "wins": 60,
        "losses": 66,
        "ties": 0,
        "winningpct": 0.476,
        "pointsfor": 11067.9,
        "pointsagainst": 10833.8,
        "pointdifferential": 234.10059,
        "pfpg": 87.8,
        "papg": 86,
        "ppgdiff": 1.8
    },
    {
        "ownerId": 10,
        "firstname": "Isaac",
        "lastinitial": "S",
        "seasons": 9,
        "wins": 60,
        "losses": 67,
        "ties": 0,
        "winningpct": 0.472,
        "pointsfor": 11023.6,
        "pointsagainst": 11210.6,
        "pointdifferential": -187,
        "pfpg": 86.8,
        "papg": 88.3,
        "ppgdiff": -1.5
    },
    {
        "ownerId": 4,
        "firstname": "Brad",
        "lastinitial": "L",
        "seasons": 9,
        "wins": 59,
        "losses": 67,
        "ties": 0,
        "winningpct": 0.468,
        "pointsfor": 10975.7,
        "pointsagainst": 11338,
        "pointdifferential": -362.2998,
        "pfpg": 87.1,
        "papg": 90,
        "ppgdiff": -2.9
    },
    {
        "ownerId": 2,
        "firstname": "Nick",
        "lastinitial": "D",
        "seasons": 9,
        "wins": 55,
        "losses": 70,
        "ties": 1,
        "winningpct": 0.44,
        "pointsfor": 10237.7,
        "pointsagainst": 10906.8,
        "pointdifferential": -669.0996,
        "pfpg": 81.3,
        "papg": 86.6,
        "ppgdiff": -5.3
    },
    {
        "ownerId": 7,
        "firstname": "Dan",
        "lastinitial": "O",
        "seasons": 9,
        "wins": 54,
        "losses": 73,
        "ties": 1,
        "winningpct": 0.425,
        "pointsfor": 10632.6,
        "pointsagainst": 11184.9,
        "pointdifferential": -552.3008,
        "pfpg": 83.1,
        "papg": 87.4,
        "ppgdiff": -4.3
    }
]
