import { Game } from '../../game';
import { MatchupStats } from '../../matchupStats';
export const matchupStats: MatchupStats = {
    "games": [
        {
            "id": 6,
            "week": 2,
            "awayTeam": {
                "id": 6,
                "name": "Orange Crush",
                "abbr": "OC",
                "owner": {
                    "id": 6,
                    "firstName": "Drew",
                    "lastInitial": "M",
                    "division": "downstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2011",
                "division": "downstairs",
                "standing": 4,
                "gamesPlayed": 16,
                "wins": 9,
                "winsRegSeason": 6,
                "losses": 7,
                "lossesRegSeason": 7,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1301,
                "pointsAgainst": 1413
            },
            "awayScore": 131,
            "homeTeam": {
                "id": 4,
                "name": "The Ricky Stanzis",
                "abbr": "RS",
                "owner": {
                    "id": 4,
                    "firstName": "Brad",
                    "lastInitial": "L",
                    "division": "upstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2011",
                "division": "upstairs",
                "standing": 3,
                "gamesPlayed": 16,
                "wins": 8,
                "winsRegSeason": 7,
                "losses": 8,
                "lossesRegSeason": 6,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1376,
                "pointsAgainst": 1411
            },
            "homeScore": 83,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 46,
            "week": 10,
            "awayTeam": {
                "id": 4,
                "name": "The Ricky Stanzis",
                "abbr": "RS",
                "owner": {
                    "id": 4,
                    "firstName": "Brad",
                    "lastInitial": "L",
                    "division": "upstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2011",
                "division": "upstairs",
                "standing": 3,
                "gamesPlayed": 16,
                "wins": 8,
                "winsRegSeason": 7,
                "losses": 8,
                "lossesRegSeason": 6,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1376,
                "pointsAgainst": 1411
            },
            "awayScore": 95,
            "homeTeam": {
                "id": 6,
                "name": "Orange Crush",
                "abbr": "OC",
                "owner": {
                    "id": 6,
                    "firstName": "Drew",
                    "lastInitial": "M",
                    "division": "downstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2011",
                "division": "downstairs",
                "standing": 4,
                "gamesPlayed": 16,
                "wins": 9,
                "winsRegSeason": 6,
                "losses": 7,
                "lossesRegSeason": 7,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1301,
                "pointsAgainst": 1413
            },
            "homeScore": 37,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 87,
            "week": 2,
            "awayTeam": {
                "id": 16,
                "name": "Orange Crush",
                "abbr": "OC",
                "owner": {
                    "id": 6,
                    "firstName": "Drew",
                    "lastInitial": "M",
                    "division": "downstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2012",
                "division": "downstairs",
                "standing": 1,
                "gamesPlayed": 15,
                "wins": 11,
                "winsRegSeason": 11,
                "losses": 4,
                "lossesRegSeason": 2,
                "ties": 0,
                "divisionWinner": "outright",
                "champion": false,
                "pointsFor": 1408.5,
                "pointsAgainst": 1187.5
            },
            "awayScore": 125,
            "homeTeam": {
                "id": 14,
                "name": "The Ricky Stanzis",
                "abbr": "RS",
                "owner": {
                    "id": 4,
                    "firstName": "Brad",
                    "lastInitial": "L",
                    "division": "upstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2012",
                "division": "upstairs",
                "standing": 1,
                "gamesPlayed": 15,
                "wins": 9,
                "winsRegSeason": 8,
                "losses": 6,
                "lossesRegSeason": 5,
                "ties": 0,
                "divisionWinner": "shared",
                "champion": false,
                "pointsFor": 1351,
                "pointsAgainst": 1289
            },
            "homeScore": 92,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 128,
            "week": 10,
            "awayTeam": {
                "id": 14,
                "name": "The Ricky Stanzis",
                "abbr": "RS",
                "owner": {
                    "id": 4,
                    "firstName": "Brad",
                    "lastInitial": "L",
                    "division": "upstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2012",
                "division": "upstairs",
                "standing": 1,
                "gamesPlayed": 15,
                "wins": 9,
                "winsRegSeason": 8,
                "losses": 6,
                "lossesRegSeason": 5,
                "ties": 0,
                "divisionWinner": "shared",
                "champion": false,
                "pointsFor": 1351,
                "pointsAgainst": 1289
            },
            "awayScore": 107.5,
            "homeTeam": {
                "id": 16,
                "name": "Orange Crush",
                "abbr": "OC",
                "owner": {
                    "id": 6,
                    "firstName": "Drew",
                    "lastInitial": "M",
                    "division": "downstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2012",
                "division": "downstairs",
                "standing": 1,
                "gamesPlayed": 15,
                "wins": 11,
                "winsRegSeason": 11,
                "losses": 4,
                "lossesRegSeason": 2,
                "ties": 0,
                "divisionWinner": "outright",
                "champion": false,
                "pointsFor": 1408.5,
                "pointsAgainst": 1187.5
            },
            "homeScore": 120.5,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 156,
            "week": 16,
            "awayTeam": {
                "id": 14,
                "name": "The Ricky Stanzis",
                "abbr": "RS",
                "owner": {
                    "id": 4,
                    "firstName": "Brad",
                    "lastInitial": "L",
                    "division": "upstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2012",
                "division": "upstairs",
                "standing": 1,
                "gamesPlayed": 15,
                "wins": 9,
                "winsRegSeason": 8,
                "losses": 6,
                "lossesRegSeason": 5,
                "ties": 0,
                "divisionWinner": "shared",
                "champion": false,
                "pointsFor": 1351,
                "pointsAgainst": 1289
            },
            "awayScore": 104.5,
            "homeTeam": {
                "id": 16,
                "name": "Orange Crush",
                "abbr": "OC",
                "owner": {
                    "id": 6,
                    "firstName": "Drew",
                    "lastInitial": "M",
                    "division": "downstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2012",
                "division": "downstairs",
                "standing": 1,
                "gamesPlayed": 15,
                "wins": 11,
                "winsRegSeason": 11,
                "losses": 4,
                "lossesRegSeason": 2,
                "ties": 0,
                "divisionWinner": "outright",
                "champion": false,
                "pointsFor": 1408.5,
                "pointsAgainst": 1187.5
            },
            "homeScore": 102,
            "gameType": "Consolation Game",
            "completed": true
        },
        {
            "id": 166,
            "week": 2,
            "awayTeam": {
                "id": 26,
                "name": "Orange Crush",
                "abbr": "OC",
                "owner": {
                    "id": 6,
                    "firstName": "Drew",
                    "lastInitial": "M",
                    "division": "downstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2013",
                "division": "downstairs",
                "standing": 3,
                "gamesPlayed": 16,
                "wins": 7,
                "winsRegSeason": 6,
                "losses": 9,
                "lossesRegSeason": 7,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1391,
                "pointsAgainst": 1420
            },
            "awayScore": 94.5,
            "homeTeam": {
                "id": 24,
                "name": "The Ricky Stanzis",
                "abbr": "RS",
                "owner": {
                    "id": 4,
                    "firstName": "Brad",
                    "lastInitial": "L",
                    "division": "upstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2013",
                "division": "upstairs",
                "standing": 5,
                "gamesPlayed": 16,
                "wins": 4,
                "winsRegSeason": 3,
                "losses": 12,
                "lossesRegSeason": 10,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1287.5,
                "pointsAgainst": 1553.5
            },
            "homeScore": 73,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 207,
            "week": 10,
            "awayTeam": {
                "id": 24,
                "name": "The Ricky Stanzis",
                "abbr": "RS",
                "owner": {
                    "id": 4,
                    "firstName": "Brad",
                    "lastInitial": "L",
                    "division": "upstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2013",
                "division": "upstairs",
                "standing": 5,
                "gamesPlayed": 16,
                "wins": 4,
                "winsRegSeason": 3,
                "losses": 12,
                "lossesRegSeason": 10,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1287.5,
                "pointsAgainst": 1553.5
            },
            "awayScore": 80,
            "homeTeam": {
                "id": 26,
                "name": "Orange Crush",
                "abbr": "OC",
                "owner": {
                    "id": 6,
                    "firstName": "Drew",
                    "lastInitial": "M",
                    "division": "downstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2013",
                "division": "downstairs",
                "standing": 3,
                "gamesPlayed": 16,
                "wins": 7,
                "winsRegSeason": 6,
                "losses": 9,
                "lossesRegSeason": 7,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1391,
                "pointsAgainst": 1420
            },
            "homeScore": 105,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 245,
            "week": 2,
            "awayTeam": {
                "id": 36,
                "name": "Orange Crush",
                "abbr": "OC",
                "owner": {
                    "id": 6,
                    "firstName": "Drew",
                    "lastInitial": "M",
                    "division": "downstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2014",
                "division": "downstairs",
                "standing": 1,
                "gamesPlayed": 16,
                "wins": 11,
                "winsRegSeason": 8,
                "losses": 5,
                "lossesRegSeason": 5,
                "ties": 0,
                "divisionWinner": "shared",
                "champion": true,
                "pointsFor": 1502,
                "pointsAgainst": 1425
            },
            "awayScore": 100,
            "homeTeam": {
                "id": 34,
                "name": "The Ricky Stanzis",
                "abbr": "RS",
                "owner": {
                    "id": 4,
                    "firstName": "Brad",
                    "lastInitial": "L",
                    "division": "upstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2014",
                "division": "upstairs",
                "standing": 2,
                "gamesPlayed": 16,
                "wins": 9,
                "winsRegSeason": 7,
                "losses": 7,
                "lossesRegSeason": 6,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1485,
                "pointsAgainst": 1373
            },
            "homeScore": 116,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 286,
            "week": 10,
            "awayTeam": {
                "id": 34,
                "name": "The Ricky Stanzis",
                "abbr": "RS",
                "owner": {
                    "id": 4,
                    "firstName": "Brad",
                    "lastInitial": "L",
                    "division": "upstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2014",
                "division": "upstairs",
                "standing": 2,
                "gamesPlayed": 16,
                "wins": 9,
                "winsRegSeason": 7,
                "losses": 7,
                "lossesRegSeason": 6,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1485,
                "pointsAgainst": 1373
            },
            "awayScore": 106.5,
            "homeTeam": {
                "id": 36,
                "name": "Orange Crush",
                "abbr": "OC",
                "owner": {
                    "id": 6,
                    "firstName": "Drew",
                    "lastInitial": "M",
                    "division": "downstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2014",
                "division": "downstairs",
                "standing": 1,
                "gamesPlayed": 16,
                "wins": 11,
                "winsRegSeason": 8,
                "losses": 5,
                "lossesRegSeason": 5,
                "ties": 0,
                "divisionWinner": "shared",
                "champion": true,
                "pointsFor": 1502,
                "pointsAgainst": 1425
            },
            "homeScore": 109,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 314,
            "week": 16,
            "awayTeam": {
                "id": 34,
                "name": "The Ricky Stanzis",
                "abbr": "RS",
                "owner": {
                    "id": 4,
                    "firstName": "Brad",
                    "lastInitial": "L",
                    "division": "upstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2014",
                "division": "upstairs",
                "standing": 2,
                "gamesPlayed": 16,
                "wins": 9,
                "winsRegSeason": 7,
                "losses": 7,
                "lossesRegSeason": 6,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1485,
                "pointsAgainst": 1373
            },
            "awayScore": 80,
            "homeTeam": {
                "id": 36,
                "name": "Orange Crush",
                "abbr": "OC",
                "owner": {
                    "id": 6,
                    "firstName": "Drew",
                    "lastInitial": "M",
                    "division": "downstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2014",
                "division": "downstairs",
                "standing": 1,
                "gamesPlayed": 16,
                "wins": 11,
                "winsRegSeason": 8,
                "losses": 5,
                "lossesRegSeason": 5,
                "ties": 0,
                "divisionWinner": "shared",
                "champion": true,
                "pointsFor": 1502,
                "pointsAgainst": 1425
            },
            "homeScore": 101.5,
            "gameType": "Super Bowl",
            "completed": true
        },
        {
            "id": 322,
            "week": 2,
            "awayTeam": {
                "id": 44,
                "name": "The Ricky Stanzis",
                "abbr": "RS",
                "owner": {
                    "id": 4,
                    "firstName": "Brad",
                    "lastInitial": "L",
                    "division": "upstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2015",
                "division": "upstairs",
                "standing": 5,
                "gamesPlayed": 16,
                "wins": 5,
                "winsRegSeason": 3,
                "losses": 11,
                "lossesRegSeason": 10,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1250,
                "pointsAgainst": 1486.5
            },
            "awayScore": 65,
            "homeTeam": {
                "id": 46,
                "name": "Orange Crush",
                "abbr": "OC",
                "owner": {
                    "id": 6,
                    "firstName": "Drew",
                    "lastInitial": "M",
                    "division": "downstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2015",
                "division": "downstairs",
                "standing": 3,
                "gamesPlayed": 16,
                "wins": 6,
                "winsRegSeason": 6,
                "losses": 10,
                "lossesRegSeason": 7,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1162,
                "pointsAgainst": 1411
            },
            "homeScore": 90.5,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 394,
            "week": 16,
            "awayTeam": {
                "id": 44,
                "name": "The Ricky Stanzis",
                "abbr": "RS",
                "owner": {
                    "id": 4,
                    "firstName": "Brad",
                    "lastInitial": "L",
                    "division": "upstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2015",
                "division": "upstairs",
                "standing": 5,
                "gamesPlayed": 16,
                "wins": 5,
                "winsRegSeason": 3,
                "losses": 11,
                "lossesRegSeason": 10,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1250,
                "pointsAgainst": 1486.5
            },
            "awayScore": 105,
            "homeTeam": {
                "id": 46,
                "name": "Orange Crush",
                "abbr": "OC",
                "owner": {
                    "id": 6,
                    "firstName": "Drew",
                    "lastInitial": "M",
                    "division": "downstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2015",
                "division": "downstairs",
                "standing": 3,
                "gamesPlayed": 16,
                "wins": 6,
                "winsRegSeason": 6,
                "losses": 10,
                "lossesRegSeason": 7,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1162,
                "pointsAgainst": 1411
            },
            "homeScore": 74,
            "gameType": "Consolation Game",
            "completed": true
        },
        {
            "id": 401,
            "week": 2,
            "awayTeam": {
                "id": 54,
                "name": "The Ricky Stanzis",
                "abbr": "RS",
                "owner": {
                    "id": 4,
                    "firstName": "Brad",
                    "lastInitial": "L",
                    "division": "upstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2016",
                "division": "upstairs",
                "standing": 1,
                "gamesPlayed": 15,
                "wins": 11,
                "winsRegSeason": 9,
                "losses": 4,
                "lossesRegSeason": 4,
                "ties": 0,
                "divisionWinner": "outright",
                "champion": true,
                "pointsFor": 1549,
                "pointsAgainst": 1411
            },
            "awayScore": 83,
            "homeTeam": {
                "id": 56,
                "name": "Orange Crush",
                "abbr": "OC",
                "owner": {
                    "id": 6,
                    "firstName": "Drew",
                    "lastInitial": "M",
                    "division": "downstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2016",
                "division": "downstairs",
                "standing": 5,
                "gamesPlayed": 16,
                "wins": 1,
                "winsRegSeason": 1,
                "losses": 15,
                "lossesRegSeason": 12,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1025,
                "pointsAgainst": 1405.5
            },
            "homeScore": 76.5,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 480,
            "week": 2,
            "awayTeam": {
                "id": 64,
                "name": "The Ricky Stanzis",
                "abbr": "RS",
                "owner": {
                    "id": 4,
                    "firstName": "Brad",
                    "lastInitial": "L",
                    "division": "upstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2017",
                "division": "upstairs",
                "standing": 1,
                "gamesPlayed": 16,
                "wins": 7,
                "winsRegSeason": 7,
                "losses": 9,
                "lossesRegSeason": 6,
                "ties": 0,
                "divisionWinner": "shared",
                "champion": false,
                "pointsFor": 1337.5,
                "pointsAgainst": 1259
            },
            "awayScore": 73,
            "homeTeam": {
                "id": 66,
                "name": "Orange Crush",
                "abbr": "OC",
                "owner": {
                    "id": 6,
                    "firstName": "Drew",
                    "lastInitial": "M",
                    "division": "downstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2017",
                "division": "downstairs",
                "standing": 1,
                "gamesPlayed": 15,
                "wins": 12,
                "winsRegSeason": 11,
                "losses": 3,
                "lossesRegSeason": 2,
                "ties": 0,
                "divisionWinner": "outright",
                "champion": false,
                "pointsFor": 1562.5,
                "pointsAgainst": 1259
            },
            "homeScore": 97,
            "gameType": "Regular Season",
            "completed": true
        },
        {
            "id": 559,
            "week": 2,
            "awayTeam": {
                "id": 74,
                "name": "The Ricky Stanzis",
                "abbr": "RS",
                "owner": {
                    "id": 4,
                    "firstName": "Brad",
                    "lastInitial": "L",
                    "division": "upstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2018",
                "division": "upstairs",
                "standing": 4,
                "gamesPlayed": 16,
                "wins": 6,
                "winsRegSeason": 5,
                "losses": 10,
                "lossesRegSeason": 8,
                "ties": 0,
                "divisionWinner": null,
                "champion": false,
                "pointsFor": 1339.7,
                "pointsAgainst": 1555
            },
            "awayScore": 94.3,
            "homeTeam": {
                "id": 76,
                "name": "Orange Crush",
                "abbr": "OC",
                "owner": {
                    "id": 6,
                    "firstName": "Drew",
                    "lastInitial": "M",
                    "division": "downstairs",
                    "handler": {},
                    "hibernateLazyInitializer": {}
                },
                "year": "2018",
                "division": "downstairs",
                "standing": 1,
                "gamesPlayed": 15,
                "wins": 9,
                "winsRegSeason": 8,
                "losses": 6,
                "lossesRegSeason": 5,
                "ties": 0,
                "divisionWinner": "shared",
                "champion": false,
                "pointsFor": 1484.9,
                "pointsAgainst": 1509.2
            },
            "homeScore": 69.7,
            "gameType": "Regular Season",
            "completed": true
        }
    ],
    "o1wins": 6,
    "o2wins": 9,
    "ties": 0,
    "o1points": 1404.7,
    "o2points": 1386.3
}
