import { Game } from '../../game';
export const playoffGames: Game[] = [
    {
        "id": 620,
        "week": 14,
        "awayTeam": {
            "id": 79,
            "name": "IFFFF's Lil' Bro",
            "abbr": "ILB",
            "owner": {
                "id": 10,
                "firstName": "Isaac",
                "lastInitial": "S",
                "division": "downstairs"
            },
            "year": "2018",
            "division": "downstairs",
            "standing": 3,
            "gamesPlayed": 16,
            "wins": 8,
            "winsRegSeason": 7,
            "losses": 8,
            "lossesRegSeason": 6,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1542.1,
            "pointsAgainst": 1465.6
        },
        "awayScore": 49.2,
        "homeTeam": {
            "id": 80,
            "name": "ROY GBIV",
            "abbr": "RGB",
            "owner": {
                "id": 11,
                "firstName": "Ryan",
                "lastInitial": "D",
                "division": "upstairs"
            },
            "year": "2018",
            "division": "upstairs",
            "standing": 2,
            "gamesPlayed": 16,
            "wins": 12,
            "winsRegSeason": 9,
            "losses": 4,
            "lossesRegSeason": 4,
            "ties": 0,
            "divisionWinner": null,
            "champion": true,
            "pointsFor": 1642.7,
            "pointsAgainst": 1427.6
        },
        "homeScore": 104.5,
        "gameType": "Quarter Final",
        "completed": true
    },
    {
        "id": 619,
        "week": 14,
        "awayTeam": {
            "id": 77,
            "name": "Ballz Tech",
            "abbr": "BT",
            "owner": {
                "id": 7,
                "firstName": "Dan",
                "lastInitial": "O",
                "division": "upstairs"
            },
            "year": "2018",
            "division": "upstairs",
            "standing": 3,
            "gamesPlayed": 16,
            "wins": 8,
            "winsRegSeason": 7,
            "losses": 8,
            "lossesRegSeason": 6,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1433.6,
            "pointsAgainst": 1555.9
        },
        "awayScore": 59.9,
        "homeTeam": {
            "id": 75,
            "name": "IOWA FOOTBALL",
            "abbr": "IFFFF",
            "owner": {
                "id": 5,
                "firstName": "Matt",
                "lastInitial": "M",
                "division": "downstairs"
            },
            "year": "2018",
            "division": "downstairs",
            "standing": 1,
            "gamesPlayed": 16,
            "wins": 10,
            "winsRegSeason": 8,
            "losses": 6,
            "lossesRegSeason": 5,
            "ties": 0,
            "divisionWinner": "shared",
            "champion": false,
            "pointsFor": 1763.1,
            "pointsAgainst": 1466.3
        },
        "homeScore": 123.7,
        "gameType": "Quarter Final",
        "completed": true
    },
    {
        "id": 623,
        "week": 15,
        "awayTeam": {
            "id": 75,
            "name": "IOWA FOOTBALL",
            "abbr": "IFFFF",
            "owner": {
                "id": 5,
                "firstName": "Matt",
                "lastInitial": "M",
                "division": "downstairs"
            },
            "year": "2018",
            "division": "downstairs",
            "standing": 1,
            "gamesPlayed": 16,
            "wins": 10,
            "winsRegSeason": 8,
            "losses": 6,
            "lossesRegSeason": 5,
            "ties": 0,
            "divisionWinner": "shared",
            "champion": false,
            "pointsFor": 1763.1,
            "pointsAgainst": 1466.3
        },
        "awayScore": 70.2,
        "homeTeam": {
            "id": 73,
            "name": "FANTastic TDs",
            "abbr": "FTTD",
            "owner": {
                "id": 3,
                "firstName": "Brian",
                "lastInitial": "K",
                "division": "upstairs"
            },
            "year": "2018",
            "division": "upstairs",
            "standing": 1,
            "gamesPlayed": 15,
            "wins": 11,
            "winsRegSeason": 11,
            "losses": 4,
            "lossesRegSeason": 2,
            "ties": 0,
            "divisionWinner": "outright",
            "champion": false,
            "pointsFor": 1629.9,
            "pointsAgainst": 1342.3
        },
        "homeScore": 68.2,
        "gameType": "Semi Final",
        "completed": true
    },
    {
        "id": 624,
        "week": 15,
        "awayTeam": {
            "id": 80,
            "name": "ROY GBIV",
            "abbr": "RGB",
            "owner": {
                "id": 11,
                "firstName": "Ryan",
                "lastInitial": "D",
                "division": "upstairs"
            },
            "year": "2018",
            "division": "upstairs",
            "standing": 2,
            "gamesPlayed": 16,
            "wins": 12,
            "winsRegSeason": 9,
            "losses": 4,
            "lossesRegSeason": 4,
            "ties": 0,
            "divisionWinner": null,
            "champion": true,
            "pointsFor": 1642.7,
            "pointsAgainst": 1427.6
        },
        "awayScore": 102.9,
        "homeTeam": {
            "id": 76,
            "name": "Orange Crush",
            "abbr": "OC",
            "owner": {
                "id": 6,
                "firstName": "Drew",
                "lastInitial": "M",
                "division": "downstairs"
            },
            "year": "2018",
            "division": "downstairs",
            "standing": 1,
            "gamesPlayed": 15,
            "wins": 9,
            "winsRegSeason": 8,
            "losses": 6,
            "lossesRegSeason": 5,
            "ties": 0,
            "divisionWinner": "shared",
            "champion": false,
            "pointsFor": 1484.9,
            "pointsAgainst": 1509.2
        },
        "homeScore": 71.9,
        "gameType": "Semi Final",
        "completed": true
    },
    {
        "id": 628,
        "week": 16,
        "awayTeam": {
            "id": 75,
            "name": "IOWA FOOTBALL",
            "abbr": "IFFFF",
            "owner": {
                "id": 5,
                "firstName": "Matt",
                "lastInitial": "M",
                "division": "downstairs"
            },
            "year": "2018",
            "division": "downstairs",
            "standing": 1,
            "gamesPlayed": 16,
            "wins": 10,
            "winsRegSeason": 8,
            "losses": 6,
            "lossesRegSeason": 5,
            "ties": 0,
            "divisionWinner": "shared",
            "champion": false,
            "pointsFor": 1763.1,
            "pointsAgainst": 1466.3
        },
        "awayScore": 107.9,
        "homeTeam": {
            "id": 80,
            "name": "ROY GBIV",
            "abbr": "RGB",
            "owner": {
                "id": 11,
                "firstName": "Ryan",
                "lastInitial": "D",
                "division": "upstairs"
            },
            "year": "2018",
            "division": "upstairs",
            "standing": 2,
            "gamesPlayed": 16,
            "wins": 12,
            "winsRegSeason": 9,
            "losses": 4,
            "lossesRegSeason": 4,
            "ties": 0,
            "divisionWinner": null,
            "champion": true,
            "pointsFor": 1642.7,
            "pointsAgainst": 1427.6
        },
        "homeScore": 117.5,
        "gameType": "Super Bowl",
        "completed": true
    }
]
