import { Game } from '../../game';
export const teamGames: Game[] = [
    {
        "id": 396,
        "week": 1,
        "awayTeam": {
            "id": 57,
            "name": "Ballz Tech",
            "abbr": "BT",
            "owner": {
                "id": 7,
                "firstName": "Dan",
                "lastInitial": "O",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 3,
            "gamesPlayed": 16,
            "wins": 7,
            "winsRegSeason": 7,
            "losses": 9,
            "lossesRegSeason": 6,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1418.5,
            "pointsAgainst": 1467.5
        },
        "awayScore": 68.5,
        "homeTeam": {
            "id": 54,
            "name": "The Ricky Stanzis",
            "abbr": "RS",
            "owner": {
                "id": 4,
                "firstName": "Brad",
                "lastInitial": "L",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 1,
            "gamesPlayed": 15,
            "wins": 11,
            "winsRegSeason": 9,
            "losses": 4,
            "lossesRegSeason": 4,
            "ties": 0,
            "divisionWinner": "outright",
            "champion": true,
            "pointsFor": 1549,
            "pointsAgainst": 1411
        },
        "homeScore": 80,
        "gameType": "Regular Season",
        "completed": true
    },
    {
        "id": 401,
        "week": 2,
        "awayTeam": {
            "id": 54,
            "name": "The Ricky Stanzis",
            "abbr": "RS",
            "owner": {
                "id": 4,
                "firstName": "Brad",
                "lastInitial": "L",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 1,
            "gamesPlayed": 15,
            "wins": 11,
            "winsRegSeason": 9,
            "losses": 4,
            "lossesRegSeason": 4,
            "ties": 0,
            "divisionWinner": "outright",
            "champion": true,
            "pointsFor": 1549,
            "pointsAgainst": 1411
        },
        "awayScore": 83,
        "homeTeam": {
            "id": 56,
            "name": "Orange Crush",
            "abbr": "OC",
            "owner": {
                "id": 6,
                "firstName": "Drew",
                "lastInitial": "M",
                "division": "downstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "downstairs",
            "standing": 5,
            "gamesPlayed": 16,
            "wins": 1,
            "winsRegSeason": 1,
            "losses": 15,
            "lossesRegSeason": 12,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1025,
            "pointsAgainst": 1405.5
        },
        "homeScore": 76.5,
        "gameType": "Regular Season",
        "completed": true
    },
    {
        "id": 406,
        "week": 3,
        "awayTeam": {
            "id": 57,
            "name": "Ballz Tech",
            "abbr": "BT",
            "owner": {
                "id": 7,
                "firstName": "Dan",
                "lastInitial": "O",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 3,
            "gamesPlayed": 16,
            "wins": 7,
            "winsRegSeason": 7,
            "losses": 9,
            "lossesRegSeason": 6,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1418.5,
            "pointsAgainst": 1467.5
        },
        "awayScore": 142,
        "homeTeam": {
            "id": 54,
            "name": "The Ricky Stanzis",
            "abbr": "RS",
            "owner": {
                "id": 4,
                "firstName": "Brad",
                "lastInitial": "L",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 1,
            "gamesPlayed": 15,
            "wins": 11,
            "winsRegSeason": 9,
            "losses": 4,
            "lossesRegSeason": 4,
            "ties": 0,
            "divisionWinner": "outright",
            "champion": true,
            "pointsFor": 1549,
            "pointsAgainst": 1411
        },
        "homeScore": 104,
        "gameType": "Regular Season",
        "completed": true
    },
    {
        "id": 411,
        "week": 4,
        "awayTeam": {
            "id": 51,
            "name": "Iowa HerkysHeroes47",
            "abbr": "IHH47",
            "owner": {
                "id": 1,
                "firstName": "Brian",
                "lastInitial": "D",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 2,
            "gamesPlayed": 16,
            "wins": 10,
            "winsRegSeason": 8,
            "losses": 6,
            "lossesRegSeason": 5,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1503.5,
            "pointsAgainst": 1361.5
        },
        "awayScore": 86,
        "homeTeam": {
            "id": 54,
            "name": "The Ricky Stanzis",
            "abbr": "RS",
            "owner": {
                "id": 4,
                "firstName": "Brad",
                "lastInitial": "L",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 1,
            "gamesPlayed": 15,
            "wins": 11,
            "winsRegSeason": 9,
            "losses": 4,
            "lossesRegSeason": 4,
            "ties": 0,
            "divisionWinner": "outright",
            "champion": true,
            "pointsFor": 1549,
            "pointsAgainst": 1411
        },
        "homeScore": 116.5,
        "gameType": "Regular Season",
        "completed": true
    },
    {
        "id": 416,
        "week": 5,
        "awayTeam": {
            "id": 59,
            "name": "Mustache Madness",
            "abbr": "MM",
            "owner": {
                "id": 10,
                "firstName": "Isaac",
                "lastInitial": "S",
                "division": "downstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "downstairs",
            "standing": 3,
            "gamesPlayed": 16,
            "wins": 7,
            "winsRegSeason": 6,
            "losses": 9,
            "lossesRegSeason": 7,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1272.5,
            "pointsAgainst": 1376.5
        },
        "awayScore": 124,
        "homeTeam": {
            "id": 54,
            "name": "The Ricky Stanzis",
            "abbr": "RS",
            "owner": {
                "id": 4,
                "firstName": "Brad",
                "lastInitial": "L",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 1,
            "gamesPlayed": 15,
            "wins": 11,
            "winsRegSeason": 9,
            "losses": 4,
            "lossesRegSeason": 4,
            "ties": 0,
            "divisionWinner": "outright",
            "champion": true,
            "pointsFor": 1549,
            "pointsAgainst": 1411
        },
        "homeScore": 140,
        "gameType": "Regular Season",
        "completed": true
    },
    {
        "id": 421,
        "week": 6,
        "awayTeam": {
            "id": 60,
            "name": "Team R.F.W.F.G.B.",
            "abbr": "FISH",
            "owner": {
                "id": 11,
                "firstName": "Ryan",
                "lastInitial": "D",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 3,
            "gamesPlayed": 16,
            "wins": 8,
            "winsRegSeason": 7,
            "losses": 8,
            "lossesRegSeason": 6,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1456.5,
            "pointsAgainst": 1403.5
        },
        "awayScore": 75.5,
        "homeTeam": {
            "id": 54,
            "name": "The Ricky Stanzis",
            "abbr": "RS",
            "owner": {
                "id": 4,
                "firstName": "Brad",
                "lastInitial": "L",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 1,
            "gamesPlayed": 15,
            "wins": 11,
            "winsRegSeason": 9,
            "losses": 4,
            "lossesRegSeason": 4,
            "ties": 0,
            "divisionWinner": "outright",
            "champion": true,
            "pointsFor": 1549,
            "pointsAgainst": 1411
        },
        "homeScore": 67.5,
        "gameType": "Regular Season",
        "completed": true
    },
    {
        "id": 426,
        "week": 7,
        "awayTeam": {
            "id": 51,
            "name": "Iowa HerkysHeroes47",
            "abbr": "IHH47",
            "owner": {
                "id": 1,
                "firstName": "Brian",
                "lastInitial": "D",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 2,
            "gamesPlayed": 16,
            "wins": 10,
            "winsRegSeason": 8,
            "losses": 6,
            "lossesRegSeason": 5,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1503.5,
            "pointsAgainst": 1361.5
        },
        "awayScore": 96.5,
        "homeTeam": {
            "id": 54,
            "name": "The Ricky Stanzis",
            "abbr": "RS",
            "owner": {
                "id": 4,
                "firstName": "Brad",
                "lastInitial": "L",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 1,
            "gamesPlayed": 15,
            "wins": 11,
            "winsRegSeason": 9,
            "losses": 4,
            "lossesRegSeason": 4,
            "ties": 0,
            "divisionWinner": "outright",
            "champion": true,
            "pointsFor": 1549,
            "pointsAgainst": 1411
        },
        "homeScore": 119.5,
        "gameType": "Regular Season",
        "completed": true
    },
    {
        "id": 431,
        "week": 8,
        "awayTeam": {
            "id": 52,
            "name": "Westside Whales",
            "abbr": "WW",
            "owner": {
                "id": 2,
                "firstName": "Nick",
                "lastInitial": "D",
                "division": "downstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "downstairs",
            "standing": 4,
            "gamesPlayed": 16,
            "wins": 8,
            "winsRegSeason": 5,
            "losses": 8,
            "lossesRegSeason": 8,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1229,
            "pointsAgainst": 1174
        },
        "awayScore": 75.5,
        "homeTeam": {
            "id": 54,
            "name": "The Ricky Stanzis",
            "abbr": "RS",
            "owner": {
                "id": 4,
                "firstName": "Brad",
                "lastInitial": "L",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 1,
            "gamesPlayed": 15,
            "wins": 11,
            "winsRegSeason": 9,
            "losses": 4,
            "lossesRegSeason": 4,
            "ties": 0,
            "divisionWinner": "outright",
            "champion": true,
            "pointsFor": 1549,
            "pointsAgainst": 1411
        },
        "homeScore": 91,
        "gameType": "Regular Season",
        "completed": true
    },
    {
        "id": 436,
        "week": 9,
        "awayTeam": {
            "id": 54,
            "name": "The Ricky Stanzis",
            "abbr": "RS",
            "owner": {
                "id": 4,
                "firstName": "Brad",
                "lastInitial": "L",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 1,
            "gamesPlayed": 15,
            "wins": 11,
            "winsRegSeason": 9,
            "losses": 4,
            "lossesRegSeason": 4,
            "ties": 0,
            "divisionWinner": "outright",
            "champion": true,
            "pointsFor": 1549,
            "pointsAgainst": 1411
        },
        "awayScore": 105,
        "homeTeam": {
            "id": 53,
            "name": "Live Free and Beathard",
            "abbr": "LFAB",
            "owner": {
                "id": 3,
                "firstName": "Brian",
                "lastInitial": "K",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 5,
            "gamesPlayed": 16,
            "wins": 8,
            "winsRegSeason": 6,
            "losses": 8,
            "lossesRegSeason": 7,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1379.5,
            "pointsAgainst": 1302.5
        },
        "homeScore": 90.5,
        "gameType": "Regular Season",
        "completed": true
    },
    {
        "id": 441,
        "week": 10,
        "awayTeam": {
            "id": 58,
            "name": "Mr. Rodgers' Neighborhood",
            "abbr": "MRN",
            "owner": {
                "id": 8,
                "firstName": "Kyle",
                "lastInitial": "P",
                "division": "downstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "downstairs",
            "standing": 1,
            "gamesPlayed": 16,
            "wins": 10,
            "winsRegSeason": 8,
            "losses": 6,
            "lossesRegSeason": 5,
            "ties": 0,
            "divisionWinner": "shared",
            "champion": false,
            "pointsFor": 1449.5,
            "pointsAgainst": 1390.5
        },
        "awayScore": 97.5,
        "homeTeam": {
            "id": 54,
            "name": "The Ricky Stanzis",
            "abbr": "RS",
            "owner": {
                "id": 4,
                "firstName": "Brad",
                "lastInitial": "L",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 1,
            "gamesPlayed": 15,
            "wins": 11,
            "winsRegSeason": 9,
            "losses": 4,
            "lossesRegSeason": 4,
            "ties": 0,
            "divisionWinner": "outright",
            "champion": true,
            "pointsFor": 1549,
            "pointsAgainst": 1411
        },
        "homeScore": 82,
        "gameType": "Regular Season",
        "completed": true
    },
    {
        "id": 446,
        "week": 11,
        "awayTeam": {
            "id": 55,
            "name": "Iowa Football",
            "abbr": "IFFFF",
            "owner": {
                "id": 5,
                "firstName": "Matt",
                "lastInitial": "M",
                "division": "downstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "downstairs",
            "standing": 1,
            "gamesPlayed": 15,
            "wins": 9,
            "winsRegSeason": 8,
            "losses": 6,
            "lossesRegSeason": 5,
            "ties": 0,
            "divisionWinner": "shared",
            "champion": false,
            "pointsFor": 1325.5,
            "pointsAgainst": 1316
        },
        "awayScore": 105,
        "homeTeam": {
            "id": 54,
            "name": "The Ricky Stanzis",
            "abbr": "RS",
            "owner": {
                "id": 4,
                "firstName": "Brad",
                "lastInitial": "L",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 1,
            "gamesPlayed": 15,
            "wins": 11,
            "winsRegSeason": 9,
            "losses": 4,
            "lossesRegSeason": 4,
            "ties": 0,
            "divisionWinner": "outright",
            "champion": true,
            "pointsFor": 1549,
            "pointsAgainst": 1411
        },
        "homeScore": 85.5,
        "gameType": "Regular Season",
        "completed": true
    },
    {
        "id": 451,
        "week": 12,
        "awayTeam": {
            "id": 60,
            "name": "Team R.F.W.F.G.B.",
            "abbr": "FISH",
            "owner": {
                "id": 11,
                "firstName": "Ryan",
                "lastInitial": "D",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 3,
            "gamesPlayed": 16,
            "wins": 8,
            "winsRegSeason": 7,
            "losses": 8,
            "lossesRegSeason": 6,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1456.5,
            "pointsAgainst": 1403.5
        },
        "awayScore": 87,
        "homeTeam": {
            "id": 54,
            "name": "The Ricky Stanzis",
            "abbr": "RS",
            "owner": {
                "id": 4,
                "firstName": "Brad",
                "lastInitial": "L",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 1,
            "gamesPlayed": 15,
            "wins": 11,
            "winsRegSeason": 9,
            "losses": 4,
            "lossesRegSeason": 4,
            "ties": 0,
            "divisionWinner": "outright",
            "champion": true,
            "pointsFor": 1549,
            "pointsAgainst": 1411
        },
        "homeScore": 116.5,
        "gameType": "Regular Season",
        "completed": true
    },
    {
        "id": 456,
        "week": 13,
        "awayTeam": {
            "id": 54,
            "name": "The Ricky Stanzis",
            "abbr": "RS",
            "owner": {
                "id": 4,
                "firstName": "Brad",
                "lastInitial": "L",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 1,
            "gamesPlayed": 15,
            "wins": 11,
            "winsRegSeason": 9,
            "losses": 4,
            "lossesRegSeason": 4,
            "ties": 0,
            "divisionWinner": "outright",
            "champion": true,
            "pointsFor": 1549,
            "pointsAgainst": 1411
        },
        "awayScore": 110,
        "homeTeam": {
            "id": 53,
            "name": "Live Free and Beathard",
            "abbr": "LFAB",
            "owner": {
                "id": 3,
                "firstName": "Brian",
                "lastInitial": "K",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 5,
            "gamesPlayed": 16,
            "wins": 8,
            "winsRegSeason": 6,
            "losses": 8,
            "lossesRegSeason": 7,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1379.5,
            "pointsAgainst": 1302.5
        },
        "homeScore": 105,
        "gameType": "Regular Season",
        "completed": true
    },
    {
        "id": 465,
        "week": 15,
        "awayTeam": {
            "id": 51,
            "name": "Iowa HerkysHeroes47",
            "abbr": "IHH47",
            "owner": {
                "id": 1,
                "firstName": "Brian",
                "lastInitial": "D",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 2,
            "gamesPlayed": 16,
            "wins": 10,
            "winsRegSeason": 8,
            "losses": 6,
            "lossesRegSeason": 5,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1503.5,
            "pointsAgainst": 1361.5
        },
        "awayScore": 70,
        "homeTeam": {
            "id": 54,
            "name": "The Ricky Stanzis",
            "abbr": "RS",
            "owner": {
                "id": 4,
                "firstName": "Brad",
                "lastInitial": "L",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 1,
            "gamesPlayed": 15,
            "wins": 11,
            "winsRegSeason": 9,
            "losses": 4,
            "lossesRegSeason": 4,
            "ties": 0,
            "divisionWinner": "outright",
            "champion": true,
            "pointsFor": 1549,
            "pointsAgainst": 1411
        },
        "homeScore": 100.5,
        "gameType": "Semi Final",
        "completed": true
    },
    {
        "id": 470,
        "week": 16,
        "awayTeam": {
            "id": 55,
            "name": "Iowa Football",
            "abbr": "IFFFF",
            "owner": {
                "id": 5,
                "firstName": "Matt",
                "lastInitial": "M",
                "division": "downstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "downstairs",
            "standing": 1,
            "gamesPlayed": 15,
            "wins": 9,
            "winsRegSeason": 8,
            "losses": 6,
            "lossesRegSeason": 5,
            "ties": 0,
            "divisionWinner": "shared",
            "champion": false,
            "pointsFor": 1325.5,
            "pointsAgainst": 1316
        },
        "awayScore": 111.5,
        "homeTeam": {
            "id": 54,
            "name": "The Ricky Stanzis",
            "abbr": "RS",
            "owner": {
                "id": 4,
                "firstName": "Brad",
                "lastInitial": "L",
                "division": "upstairs",
                "handler": {},
                "hibernateLazyInitializer": {}
            },
            "year": "2016",
            "division": "upstairs",
            "standing": 1,
            "gamesPlayed": 15,
            "wins": 11,
            "winsRegSeason": 9,
            "losses": 4,
            "lossesRegSeason": 4,
            "ties": 0,
            "divisionWinner": "outright",
            "champion": true,
            "pointsFor": 1549,
            "pointsAgainst": 1411
        },
        "homeScore": 148,
        "gameType": "Super Bowl",
        "completed": true
    }
]
