import { Game } from './game';
// import { TestGame } from './testGame';
// export const recentGames: TestGame[] = [
export const recentGames: Game[] = [
    {
        "id": 614,
        "week": 13,
        "awayTeam": {
            "id": 74,
            "name": "The Ricky Stanzis",
            "abbr": "RS",
            "owner": {
                "id": 4,
                "firstName": "Brad",
                "lastInitial": "L",
                "division": "upstairs"
            },
            "year": "2018",
            "division": "upstairs",
            "standing": 4,
            "gamesPlayed": 13,
            "wins": 5,
            "winsRegSeason": 5,
            "losses": 8,
            "lossesRegSeason": 8,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1119.7,
            "pointsAgainst": 1270.6
        },
        "awayScore": 72.6,
        "homeTeam": {
            "id": 73,
            "name": "FANTastic TDs",
            "abbr": "FTTD",
            "owner": {
                "id": 3,
                "firstName": "Brian",
                "lastInitial": "K",
                "division": "upstairs"
            },
            "year": "2018",
            "division": "upstairs",
            "standing": 1,
            "gamesPlayed": 13,
            "wins": 11,
            "winsRegSeason": 11,
            "losses": 2,
            "lossesRegSeason": 2,
            "ties": 0,
            "divisionWinner": "outright",
            "champion": false,
            "pointsFor": 1464,
            "pointsAgainst": 1165.7
        },
        "homeScore": 95.4,
        "gameType": "Regular Season",
        "completed": true
    },
    {
        "id": 615,
        "week": 13,
        "awayTeam": {
            "id": 75,
            "name": "IOWA FOOTBALL",
            "abbr": "IFFFF",
            "owner": {
                "id": 5,
                "firstName": "Matt",
                "lastInitial": "M",
                "division": "downstairs"
            },
            "year": "2018",
            "division": "downstairs",
            "standing": 1,
            "gamesPlayed": 13,
            "wins": 8,
            "winsRegSeason": 8,
            "losses": 5,
            "lossesRegSeason": 5,
            "ties": 0,
            "divisionWinner": "shared",
            "champion": false,
            "pointsFor": 1461.3,
            "pointsAgainst": 1220.7
        },
        "awayScore": 122.4,
        "homeTeam": {
            "id": 79,
            "name": "IFFFF's Lil' Bro",
            "abbr": "ILB",
            "owner": {
                "id": 10,
                "firstName": "Isaac",
                "lastInitial": "S",
                "division": "downstairs"
            },
            "year": "2018",
            "division": "downstairs",
            "standing": 3,
            "gamesPlayed": 13,
            "wins": 7,
            "winsRegSeason": 7,
            "losses": 6,
            "lossesRegSeason": 6,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1322,
            "pointsAgainst": 1213.1
        },
        "homeScore": 88.2,
        "gameType": "Regular Season",
        "completed": true
    },
    {
        "id": 616,
        "week": 13,
        "awayTeam": {
            "id": 76,
            "name": "Orange Crush",
            "abbr": "OC",
            "owner": {
                "id": 6,
                "firstName": "Drew",
                "lastInitial": "M",
                "division": "downstairs"
            },
            "year": "2018",
            "division": "downstairs",
            "standing": 1,
            "gamesPlayed": 13,
            "wins": 8,
            "winsRegSeason": 8,
            "losses": 5,
            "lossesRegSeason": 5,
            "ties": 0,
            "divisionWinner": "shared",
            "champion": false,
            "pointsFor": 1306.6,
            "pointsAgainst": 1308.6
        },
        "awayScore": 73.4,
        "homeTeam": {
            "id": 71,
            "name": "Iowa HerkysHeroes47",
            "abbr": "IHH47",
            "owner": {
                "id": 1,
                "firstName": "Brian",
                "lastInitial": "D",
                "division": "upstairs"
            },
            "year": "2018",
            "division": "upstairs",
            "standing": 4,
            "gamesPlayed": 13,
            "wins": 5,
            "winsRegSeason": 5,
            "losses": 8,
            "lossesRegSeason": 8,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1304.4,
            "pointsAgainst": 1362.3
        },
        "homeScore": 116,
        "gameType": "Regular Season",
        "completed": true
    },
    {
        "id": 617,
        "week": 13,
        "awayTeam": {
            "id": 72,
            "name": "Westside Whales",
            "abbr": "WW",
            "owner": {
                "id": 2,
                "firstName": "Nick",
                "lastInitial": "D",
                "division": "downstairs"
            },
            "year": "2018",
            "division": "downstairs",
            "standing": 5,
            "gamesPlayed": 13,
            "wins": 2,
            "winsRegSeason": 2,
            "losses": 11,
            "lossesRegSeason": 11,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1121.3,
            "pointsAgainst": 1384.1
        },
        "awayScore": 69.1,
        "homeTeam": {
            "id": 78,
            "name": "Mr. Rodgers' Neighborhood",
            "abbr": "MRN",
            "owner": {
                "id": 8,
                "firstName": "Kyle",
                "lastInitial": "P",
                "division": "downstairs"
            },
            "year": "2018",
            "division": "downstairs",
            "standing": 4,
            "gamesPlayed": 13,
            "wins": 3,
            "winsRegSeason": 3,
            "losses": 10,
            "lossesRegSeason": 10,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1037.4,
            "pointsAgainst": 1295.2
        },
        "homeScore": 70.3,
        "gameType": "Regular Season",
        "completed": true
    },
    {
        "id": 618,
        "week": 13,
        "awayTeam": {
            "id": 80,
            "name": "ROY GBIV",
            "abbr": "RGB",
            "owner": {
                "id": 11,
                "firstName": "Ryan",
                "lastInitial": "D",
                "division": "upstairs"
            },
            "year": "2018",
            "division": "upstairs",
            "standing": 2,
            "gamesPlayed": 13,
            "wins": 9,
            "winsRegSeason": 9,
            "losses": 4,
            "lossesRegSeason": 4,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1317.8,
            "pointsAgainst": 1198.6
        },
        "awayScore": 67.4,
        "homeTeam": {
            "id": 77,
            "name": "Ballz Tech",
            "abbr": "BT",
            "owner": {
                "id": 7,
                "firstName": "Dan",
                "lastInitial": "O",
                "division": "upstairs"
            },
            "year": "2018",
            "division": "upstairs",
            "standing": 3,
            "gamesPlayed": 13,
            "wins": 7,
            "winsRegSeason": 7,
            "losses": 6,
            "lossesRegSeason": 6,
            "ties": 0,
            "divisionWinner": null,
            "champion": false,
            "pointsFor": 1225.7,
            "pointsAgainst": 1261.3
        },
        "homeScore": 105.2,
        "gameType": "Regular Season",
        "completed": true
    }
]
