export class TeamGame {
  week: number;
  team: string;
  owner: string;
  home: string;
  opposingTeam: string;
  opposingTeamId: number;
  opposingOwner: string;
  opposingOwnerId: number;
  division: string;
  result: string;
  teamScore: number;
  opponentScore: number;
  gameType: string;
  completed: boolean;
  w: number;
  l: number;
  t: number;
  fullStreak: string;
};
